### ISSUE TITLE
Create example-page

### ISSUE THREAD

**Issue by iamfrank** [SDFIdk/gsearch-ui#1]

**Comment by iamfrank** [comment]
A Github workflow has been provided, that deploys a demo page at https://sdfidk.github.io/gsearch-ui/

**Comment by DocDemar** [comment]
great - er det Ok at komme med ønsker til siden?

**Comment by iamfrank** [comment]
> great - er det Ok at komme med ønsker til siden?

Yup. Gerne opret som nye issues.
