### ISSUE TITLE
link til dokumentation

### ISSUE THREAD

**Issue by DocDemar** [SDFIdk/gsearch-ui#3]
link til docs , dataforsyningen.dk og github repo

og link fra de tre ovenstående til geosearch-ui siden

**Comment by Gebuz** [comment]
Har tilføjet links mellem demosiden og github repo, hvor på dataforsyningen.dk skal der linkes til GSearch-UI? skal det i labs?

**Comment by DocDemar** [comment]
> Har tilføjet links mellem demosiden og github repo. Hvor på dataforsyningen.dk skal der linkes til GSearch-UI? skal det i labs?

I beskrivelsen af gsearch på dataforsyningen.dk kunne skal der være link til 
https://github.com/SDFIdk/gsearch
https://github.com/SDFIdk/gsearch-ui

**Comment by Gebuz** [comment]
https://dataforsyningen.dk/news/4861
Indholder nu links til begge.
