### ISSUE TITLE
Frederik 7 Vej

### ISSUE THREAD

**Issue by AnnetteSDFE** [SDFIdk/gsearch-ui#32]
Frederik 7 Vej, viser i et splitsekund det rigtige vejnavn, men går så over i at foreslå ”Frederik Grams Vej”

![image](https://user-images.githubusercontent.com/72433485/212829010-09388e1b-810b-4654-a4d4-69219725fef8.png)

**Comment by Gebuz** [comment]
Jeg kan ikke replikere denne fejl, jeg får det rigtige resultat.
![image](https://user-images.githubusercontent.com/6773230/212883761-06dbf1b7-f828-4881-ad27-d6df184a2ec3.png)

**Comment by AnnetteSDFE** [comment]
jeg får også "Frederik 7 Vej" til at starte med når jeg søger på "frederik 7" men efter ca 5 sek får jeg frederik gramsvej op i stedet

**Comment by Gebuz** [comment]
Tak, jeg har fundet fejlen. Det skyldes at kaldene til backenden tager så lang tid at de kommer i forkert rækkefølge. Frontenden skal droppe det første kald når det starter et nyt.

flytter til #33
