### ISSUE TITLE
Get coordinates in wgs84

### ISSUE THREAD

**Issue by baffioso** [SDFIdk/gsearch-ui#35]
Is it possible to configure g-search to return coordinates in wgs84 instead of euref89 (EPSG:25832)?

Looks like API only supports EPSG:25832
https://github.com/SDFIdk/gsearch/tree/main/doc#response

**Comment by Gebuz** [comment]
Correct, the backend does not support other projections yet. Once it does support it it will be added in gsearch-ui aswell.
https://github.com/SDFIdk/gsearch/issues/122
