### ISSUE TITLE
Error when using filter parameter

### ISSUE THREAD

**Issue by sweco-dkgemr** [SDFIdk/gsearch-ui#41]
When using the filter parameter many of the calls to the API fails with a status code 400 with the error '**BAD_REQUEST**' and the error message '**Input invalid**'. Because of that the search result is of very poor quality, since sometimes 2 or 3 resources are left out of the result list due to the failing calls. This is quite critical for us - since most of our customers uses the filter parameter. 

![Error_1](https://github.com/SDFIdk/gsearch-ui/assets/62336024/05227e10-d434-4ccc-badd-c6ddee5838fa)

![error_2](https://github.com/SDFIdk/gsearch-ui/assets/62336024/a261c780-3925-4c70-8a7d-8d9d6d735ba8)

Since the new API v.1.1 has replaced the old API v.1.0 - it affects all our customers who have already switched from GeoSearch to GSearch.

**Comment by DocDemar** [comment]
det foregående issue er flyttet til dette repo https://github.com/SDFIdk/gsearch/issues/202
