### ISSUE TITLE
Vis kun resultater for udvalgte kommuner

### ISSUE THREAD

**Issue by baffioso** [SDFIdk/gsearch-ui#43]
Jeg er interesseret i at lave adressesøgning som udelukkende dækker København. Er det muligt at sætte kommunefilter, så gsearch kun returnerer adresser fra en eller flere specifikke kommuner?

Indtil videre er jeg lykkedes med at angive filteret sammen med min token, men er ikke så kønt:
```html
<g-search data-token="<TOKEN>&filter=kommunekode%20like%20%27%250101%25%27"
          class="gsearch"
          data-resources="husnummer"
          data-limit="10"
          data-placeholder="Søg adresse...">
</g-search>
```

**Comment by iamfrank** [comment]
Kreativt, må jeg sige. Vi skal måske være lidt mere opmærksomme på validering af tokens :)
Vi kan nok hurtigt lave en `filter`-attribut i stedet, så du ikke skal hacke via token-attribute.

**Comment by iamfrank** [comment]
@baffioso Giv det et shot med den opdaterede version. Du kan sætte filter som
```
<g-search data-token="<TOKEN>"
          class="gsearch"
          data-resources="husnummer"
          data-limit="10"
          data-placeholder="Søg adresse..."
          data-filter="kommunekode like '%0461%'">
</g-search>
```

**Comment by baffioso** [comment]
Tak.

Ved du hvornår den bliver tilgængelig via NPM, så jeg kan få den ind i mit projekt den vej igennem?

**Comment by iamfrank** [comment]
npm-pakke v1.2.0 er ude nu.

**Comment by baffioso** [comment]
Den nye filterattribut spiller - tak
![gsearch](https://github.com/SDFIdk/gsearch-ui/assets/7534153/1407d847-e42d-4d6e-b3e0-207b98f790b0)
