### ISSUE TITLE
Missing handling of MultiLineString 

### ISSUE THREAD

**Issue by AAFredsted** [SDFIdk/gsearch-ui#51]
Ved søgning på Sti'er i stednavne fejler søgeværktøjet. Stednavne kan forekomme som MultiPoint, MultiPolygon eller MultiLineString, og i implementationen på https://github.com/SDFIdk/skraafoto_frontend mangler der en håndtering af MultiLineString.

![image](https://github.com/user-attachments/assets/551faeb0-8363-460f-b30e-afb2e360b436)

**Comment by Gebuz** [comment]
Jeg kan se at du har lavet en PR på skraafoto, så jeg lukker det her issue :)
